# Identificador del proyecto (debe coincidir con el Project key en SonarCloud)
sonar.projectKey=INFRA-UPAO_everywheretravel
sonar.projectName=everywheretravel
sonar.projectVersion=1.0
sonar.organization=infra-upao

# Codigo a analizar: IaC + aplicaciones
sonar.sources=iac,apps/backend/src/main,apps/frontend/src,apps/lambda-doc-generator
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts

# El analizador de Java requiere el bytecode compilado (mvn compile en el workflow)
sonar.java.binaries=apps/backend/target/classes

# Codificacion de los archivos
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.terraform.provider.aws.version=6.50.0
