--
-- PostgreSQL database dump
--

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carpetas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carpetas (
    carp_id_int integer NOT NULL,
    carp_upd_tmp timestamp(6) without time zone,
    carp_cre_tmp timestamp(6) without time zone,
    carp_desc_vac character varying(32600),
    carp_niv_int integer,
    carp_nom_vac character varying(255),
    car_id_padr_int integer
);


--
-- Name: carpetas_carp_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carpetas ALTER COLUMN carp_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carpetas_carp_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias (
    cat_id_int integer NOT NULL,
    cat_upd_tmp timestamp(6) without time zone,
    cat_cre_tmp timestamp(6) without time zone,
    cat_nom_vac character varying(100)
);


--
-- Name: categorias_cat_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias ALTER COLUMN cat_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_cat_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias_personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias_personas (
    cat_per_id_int integer NOT NULL,
    cat_per_upd_tmp timestamp(6) without time zone,
    cat_per_cre_tmp timestamp(6) without time zone,
    cat_per_desc_vac character varying(255),
    cat_per_nom_vac character varying(255)
);


--
-- Name: categorias_personas_cat_per_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias_personas ALTER COLUMN cat_per_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_personas_cat_per_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: correos_personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.correos_personas (
    corre_id_int integer NOT NULL,
    corre_upd_tmp timestamp(6) without time zone,
    corre_cre_tmp timestamp(6) without time zone,
    corre_emai_vac character varying(100) NOT NULL,
    corre_tipo_vac character varying(20),
    per_id_int integer
);


--
-- Name: correos_personas_corre_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.correos_personas ALTER COLUMN corre_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.correos_personas_corre_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cotizaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cotizaciones (
    cot_id_int integer NOT NULL,
    cot_fec_upd_tmp timestamp(6) without time zone,
    cot_cant_adlt_int integer,
    cot_cant_dchd_int integer,
    cot_num_vac character varying(255),
    cot_fec_emi_tmp timestamp(6) without time zone,
    cot_fec_reg_tmp date,
    cot_fec_sal_tmp date,
    cot_fec_venc_tmp timestamp(6) without time zone,
    cot_mon_vac character varying(255),
    cot_nomb_vac character varying(255),
    cot_obs_vac character varying(32600),
    cot_dest_vac character varying(255),
    carp_id_padr_int integer,
    cou_id_int integer,
    est_cot_id_int integer,
    form_id_int integer,
    per_id_int integer,
    suc_id_int integer
);


--
-- Name: cotizaciones_cot_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cotizaciones ALTER COLUMN cot_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotizaciones_cot_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: counter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.counter (
    cou_id_int integer NOT NULL,
    cou_cod_vac character varying(50),
    cou_est_bol boolean,
    cou_fec_actu_tmp timestamp(6) without time zone,
    cou_fec_crea_tmp timestamp(6) without time zone,
    cou_nom_vac character varying(150)
);


--
-- Name: counter_cou_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.counter ALTER COLUMN cou_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.counter_cou_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_cotizacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_cotizacion (
    dcot_id_int integer NOT NULL,
    dcot_upd_tmp timestamp(6) without time zone,
    dcot_cant_int integer,
    dcot_comision_dc numeric(38,2),
    dcot_cre_tmp timestamp(6) without time zone,
    dcot_desc_vac character varying(32600),
    dcot_prec_hist_dc numeric(38,2),
    dcot_select_bol boolean,
    dcot_und_int integer,
    cat_id_int integer,
    cot_id_int integer NOT NULL,
    opr_id_int integer,
    prod_id_int integer,
    prov_id_int integer
);


--
-- Name: detalle_cotizacion_dcot_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_cotizacion ALTER COLUMN dcot_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_cotizacion_dcot_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_documento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_documento (
    dtdoc_id_int integer NOT NULL,
    dtdoc_upd_tmp timestamp(6) without time zone,
    dtdoc_cre_tmp timestamp(6) without time zone,
    dtdoc_fec_emi_tmp date,
    dtdoc_fec_ven_tmp date,
    dtdoc_numero_vac character varying(255),
    dtdoc_ori_vac character varying(255),
    doc_id_int integer,
    per_nat_id_int integer
);


--
-- Name: detalle_documento_cobranza; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_documento_cobranza (
    det_doc_co_id_int bigint NOT NULL,
    det_doc_co_cant_int integer,
    det_doc_co_desc_vac character varying(32600),
    det_doc_co_cre_tmp timestamp(6) without time zone,
    det_doc_co_prec_dc numeric(38,2),
    doc_co_id_int bigint,
    prod_id_int integer
);


--
-- Name: detalle_documento_cobranza_det_doc_co_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_documento_cobranza ALTER COLUMN det_doc_co_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_documento_cobranza_det_doc_co_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_documento_dtdoc_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_documento ALTER COLUMN dtdoc_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_documento_dtdoc_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_liquidacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_liquidacion (
    dtliq_id_int integer NOT NULL,
    dtliq_fec_upd_tmp timestamp(6) without time zone,
    dtliq_bol_fac_pasj_vac character varying(255),
    dtliq_carg_serv_dc numeric(38,2),
    dtliq_comision_vac character varying(255),
    dtliq_cost_tick_dc numeric(38,2),
    dtliq_fec_cre_tmp timestamp(6) without time zone,
    dtliq_doc_cobr_vac character varying(255),
    dtliq_doc_fee_vac character varying(255),
    dtliq_fac_comp_vac character varying(255),
    dtliq_fee_emision_vac character varying(255),
    dtliq_mont_desct_dc numeric(38,2),
    dtliq_pag_pax_sol_dc numeric(38,2),
    dtliq_pag_pax_dol_dc numeric(38,2),
    dtliq_tick_vac character varying(255),
    dtliq_val_vent_dc numeric(38,2),
    liq_id_int integer NOT NULL,
    opr_id_int integer,
    prod_id_int integer,
    prov_id_int integer,
    via_id_int integer
);


--
-- Name: detalle_liquidacion_dtliq_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_liquidacion ALTER COLUMN dtliq_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_liquidacion_dtliq_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_recibo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_recibo (
    det_recibo_id_int integer NOT NULL,
    det_recibo_cant_int integer,
    det_recibo_desc_vac character varying(32600),
    det_recibo_upd_tmp timestamp(6) without time zone,
    det_recibo_cre_tmp timestamp(6) without time zone,
    det_recibo_prec_dc numeric(38,2),
    prod_id_int integer,
    recibo_id_int integer
);


--
-- Name: detalle_recibo_det_recibo_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_recibo ALTER COLUMN det_recibo_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_recibo_det_recibo_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documento_cobranza; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documento_cobranza (
    doc_co_id_int bigint NOT NULL,
    doc_co_corre_int integer,
    doc_co_cos_env_dc double precision,
    created_at timestamp(6) without time zone NOT NULL,
    doc_co_fec_emi_tmp date,
    doc_co_file_ven_vac character varying(255),
    doc_co_mon_vac character varying(255),
    doc_co_obs_vac character varying(32600),
    doc_co_serie_vac character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    carp_id_int integer,
    cot_id_int integer,
    dtdoc_id_int integer,
    form_id_int integer,
    per_id_int integer,
    per_jur_id_int integer,
    suc_id_int integer,
    usr_id_int integer
);


--
-- Name: documento_cobranza_doc_co_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documento_cobranza ALTER COLUMN doc_co_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documento_cobranza_doc_co_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos (
    doc_id_int integer NOT NULL,
    doc_upd_tmp timestamp(6) without time zone,
    doc_cre_tmp timestamp(6) without time zone,
    doc_desc_vac character varying(32600),
    doc_est_bln boolean,
    doc_tipo_vac character varying(255) NOT NULL
);


--
-- Name: documentos_doc_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos ALTER COLUMN doc_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_doc_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estados_cotizacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_cotizacion (
    est_cot_id_int integer NOT NULL,
    est_cot_desc_vac character varying(200),
    est_cot_upd_tmp timestamp(6) without time zone,
    est_cot_cre_tmp timestamp(6) without time zone
);


--
-- Name: estados_cotizacion_est_cot_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estados_cotizacion ALTER COLUMN est_cot_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_cotizacion_est_cot_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forma_pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forma_pago (
    form_id_int integer NOT NULL,
    form_cod_int integer,
    form_desc_vac character varying(200),
    form_upd_vac timestamp(6) without time zone,
    form_cre_vac timestamp(6) without time zone
);


--
-- Name: forma_pago_form_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.forma_pago ALTER COLUMN form_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forma_pago_form_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_cotizaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historial_cotizaciones (
    hist_cot_id_int integer NOT NULL,
    hist_cot_cre_tmp timestamp(6) without time zone,
    hist_cot_obs_vac character varying(500),
    hist_cot_uuid uuid DEFAULT gen_random_uuid(),
    cot_id_int integer,
    est_cot_id_int integer,
    usr_id_int integer
);


--
-- Name: historial_cotizaciones_hist_cot_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historial_cotizaciones ALTER COLUMN hist_cot_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_cotizaciones_hist_cot_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: liquidacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.liquidacion (
    liq_id_int integer NOT NULL,
    liq_fec_upd_tmp timestamp(6) without time zone,
    liq_fec_cre_tmp timestamp(6) without time zone,
    liq_dest_vac character varying(255),
    liq_fec_comp_tmp date,
    liq_num_vac character varying(255),
    liq_nro_pasj_int integer,
    carp_id_padr_int integer,
    cot_id_int integer,
    form_id_int integer,
    prod_id_int integer
);


--
-- Name: liquidacion_liq_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.liquidacion ALTER COLUMN liq_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.liquidacion_liq_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: natural_juridico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.natural_juridico (
    nat_jur_id_int integer NOT NULL,
    nat_jur_upd_tmp timestamp(6) without time zone,
    nat_jur_cre_tmp timestamp(6) without time zone,
    per_jur_id_int integer NOT NULL,
    per_nat_id_int integer NOT NULL
);


--
-- Name: natural_juridico_nat_jur_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.natural_juridico ALTER COLUMN nat_jur_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.natural_juridico_nat_jur_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: observacion_liquidacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.observacion_liquidacion (
    obliq_id_int bigint NOT NULL,
    obliq_fec_upd_tmp timestamp(6) without time zone,
    obliq_fec_cre_tmp timestamp(6) without time zone,
    obliq_desc_vac character varying(255),
    obliq_doc_vac character varying(255),
    obliq_nro_doc_vac character varying(255),
    obliq_val_dc numeric(38,2),
    liq_id_int integer NOT NULL
);


--
-- Name: observacion_liquidacion_obliq_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.observacion_liquidacion ALTER COLUMN obliq_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.observacion_liquidacion_obliq_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operador (
    opr_id_int integer NOT NULL,
    opr_upd_tmp timestamp(6) without time zone,
    opr_cre_tmp timestamp(6) without time zone,
    opr_nomb_int character varying(150)
);


--
-- Name: operador_opr_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.operador ALTER COLUMN opr_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operador_opr_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pago_pax; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pago_pax (
    pax_id_int integer NOT NULL,
    pax_fec_upd_tmp timestamp(6) without time zone,
    pax_fec_cre_tmp timestamp(6) without time zone,
    pax_detalle_vac character varying(500),
    pax_moned_vac character varying(10),
    pax_monto_dc numeric(10,2),
    form_id_int integer,
    liq_id_int integer
);


--
-- Name: pago_pax_pax_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pago_pax ALTER COLUMN pax_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_pax_pax_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona_juridica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona_juridica (
    per_jurd_id_int integer NOT NULL,
    per_jurd_upd_tmp timestamp(6) without time zone,
    per_jurd_cre_tmp timestamp(6) without time zone,
    per_jurd_raz_social_vac character varying(255),
    per_jurd_ruc_int character varying(255),
    per_id_int integer NOT NULL
);


--
-- Name: persona_juridica_per_jurd_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona_juridica ALTER COLUMN per_jurd_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_juridica_per_jurd_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona_natural; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona_natural (
    per_nat_id_int integer NOT NULL,
    per_nat_upd_tmp timestamp(6) without time zone,
    per_nat_apell_mat_vac character varying(255),
    per_nat_apell_pat_vac character varying(255),
    per_nat_cre_tmp timestamp(6) without time zone,
    per_nat_doc_int character varying(255),
    per_nat_nomb_vac character varying(255),
    per_nat_sexo_vac character varying(255),
    cat_per_id_int integer,
    per_id_int integer NOT NULL,
    via_id_int integer
);


--
-- Name: persona_natural_per_nat_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona_natural ALTER COLUMN per_nat_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_natural_per_nat_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas (
    per_id_int integer NOT NULL,
    per_upd_tmp timestamp(6) without time zone,
    per_cre_tmp timestamp(6) without time zone,
    per_direc_vac character varying(255),
    per_email_vac character varying(255),
    per_obs_vac character varying(32600)
);


--
-- Name: personas_cotizaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_cotizaciones (
    cot_id_int integer NOT NULL,
    per_id_int integer NOT NULL
);


--
-- Name: personas_per_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personas ALTER COLUMN per_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas_per_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos (
    prod_id_int integer NOT NULL,
    prod_upd_tmp timestamp(6) without time zone,
    prod_cre_tmp timestamp(6) without time zone,
    prod_desc_vac character varying(255),
    prod_tipo_vac character varying(100)
);


--
-- Name: productos_prod_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos ALTER COLUMN prod_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_prod_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proveedor (
    prov_id_int integer NOT NULL,
    prov_upd_tmp timestamp(6) without time zone,
    prov_cre_tmp timestamp(6) without time zone,
    prov_nomb_vac character varying(150),
    prov_nom_jur_vac character varying(255),
    prov_ruc_int integer
);


--
-- Name: proveedor_colaborador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proveedor_colaborador (
    prov_col_id_int integer NOT NULL,
    prov_col_upd_tmp timestamp(6) without time zone,
    prov_col_cargo_int character varying(100),
    prov_col_cod_pais_vac character varying(10),
    prov_col_cre_tmp timestamp(6) without time zone,
    pro_col_detalle_vac character varying(500),
    prov_col_email_int character varying(150),
    prov_col_nom_vac character varying(150),
    prov_col_telf_int character varying(50),
    prov_id_int integer
);


--
-- Name: proveedor_colaborador_prov_col_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proveedor_colaborador ALTER COLUMN prov_col_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_colaborador_prov_col_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedor_contacto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proveedor_contacto (
    prov_cont_id_int integer NOT NULL,
    prov_col_upd_tmp timestamp(6) without time zone,
    prov_cont_cod_pais_vac character varying(5),
    prov_col_cre_tmp timestamp(6) without time zone,
    prov_cont_desc_int character varying(300),
    prov_cont_email_vac character varying(150),
    prov_cont_numero_vac character varying(50),
    prov_grup_id_int integer,
    prov_id_int integer
);


--
-- Name: proveedor_contacto_prov_cont_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proveedor_contacto ALTER COLUMN prov_cont_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_contacto_prov_cont_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedor_grupo_contacto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proveedor_grupo_contacto (
    prov_grup_id_int integer NOT NULL,
    cat_upd_tmp timestamp(6) without time zone,
    cat_cre_tmp timestamp(6) without time zone,
    prov_grup_dec_vac character varying(300),
    prov_grup_nom_vac character varying(150)
);


--
-- Name: proveedor_grupo_contacto_prov_grup_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proveedor_grupo_contacto ALTER COLUMN prov_grup_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_grupo_contacto_prov_grup_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedor_prov_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proveedor ALTER COLUMN prov_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_prov_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recibo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recibo (
    recibo_id_int integer NOT NULL,
    recibo_corre_vac integer,
    recibo_created_at timestamp(6) without time zone NOT NULL,
    recibo_fec_emi_tmp date,
    recibo_fec_ven_tmp date,
    recibo_file_ven_vac character varying(255),
    recibo_mon_vac character varying(255),
    recibo_obs_vac character varying(32600),
    recibo_serie_vac character varying(255),
    recibo_updated_at timestamp(6) without time zone NOT NULL,
    carp_id_int integer,
    cot_id_int integer,
    dtdoc_id_int integer,
    form_id_int integer,
    per_id_int integer,
    per_jur_id_int integer,
    suc_id_int integer,
    usr_id_int integer
);


--
-- Name: recibo_recibo_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recibo ALTER COLUMN recibo_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recibo_recibo_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role (
    rol_id integer NOT NULL,
    prov_upd_tmp timestamp(6) without time zone,
    prov_cre_tmp timestamp(6) without time zone,
    rol_nam_vc character varying(100)
);


--
-- Name: role_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role ALTER COLUMN rol_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sucursal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sucursal (
    suc_id_int integer NOT NULL,
    suc_desc_vac character varying(200),
    suc_direc_vac character varying(300),
    suc_emai_vac character varying(100),
    suc_esta_bool boolean,
    suc_act_tmp timestamp(6) without time zone,
    suc_cre_tmp timestamp(6) without time zone,
    suc_tele_vac character varying(255)
);


--
-- Name: sucursal_suc_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sucursal ALTER COLUMN suc_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sucursal_suc_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telefonos_personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telefonos_personas (
    tel_id_int integer NOT NULL,
    tel_per_upd_tmp timestamp(6) without time zone,
    tel_cod_vac character varying(5),
    tel_per_cre_tmp timestamp(6) without time zone,
    tel_desc_vac character varying(32600),
    tel_num_vac character varying(20),
    tel_tipo_vac character varying(15),
    per_id_int integer
);


--
-- Name: telefonos_personas_tel_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.telefonos_personas ALTER COLUMN tel_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telefonos_personas_tel_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    usr_id_int integer NOT NULL,
    prov_upd_tmp timestamp(6) without time zone,
    prov_cre_tmp timestamp(6) without time zone,
    usr_email_vc character varying(150),
    rol_nam_vc character varying(100),
    usr_pass_vc character varying(255),
    rol_id integer NOT NULL,
    suc_id_int integer
);


--
-- Name: usuarios_usr_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN usr_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usr_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viajeros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.viajeros (
    via_id_int integer NOT NULL,
    via_upd_tmp timestamp(6) without time zone,
    via_cre_tmp timestamp(6) without time zone,
    via_fec_nac_tmp date,
    via_nacio_vac character varying(255),
    via_resi_vac character varying(255)
);


--
-- Name: viajeros_frecuente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.viajeros_frecuente (
    via_frec_id_int integer NOT NULL,
    via_upd_tmp timestamp(6) without time zone,
    via_frec_aer_vac character varying(255),
    via_frec_cod_vac character varying(255),
    via_cre_tmp timestamp(6) without time zone,
    via_id_int integer
);


--
-- Name: viajeros_frecuente_via_frec_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.viajeros_frecuente ALTER COLUMN via_frec_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viajeros_frecuente_via_frec_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viajeros_via_id_int_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.viajeros ALTER COLUMN via_id_int ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viajeros_via_id_int_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carpetas carpetas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carpetas
    ADD CONSTRAINT carpetas_pkey PRIMARY KEY (carp_id_int);


--
-- Name: categorias_personas categorias_personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias_personas
    ADD CONSTRAINT categorias_personas_pkey PRIMARY KEY (cat_per_id_int);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (cat_id_int);


--
-- Name: correos_personas correos_personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.correos_personas
    ADD CONSTRAINT correos_personas_pkey PRIMARY KEY (corre_id_int);


--
-- Name: cotizaciones cotizaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT cotizaciones_pkey PRIMARY KEY (cot_id_int);


--
-- Name: counter counter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counter
    ADD CONSTRAINT counter_pkey PRIMARY KEY (cou_id_int);


--
-- Name: detalle_cotizacion detalle_cotizacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_cotizacion
    ADD CONSTRAINT detalle_cotizacion_pkey PRIMARY KEY (dcot_id_int);


--
-- Name: detalle_documento_cobranza detalle_documento_cobranza_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_documento_cobranza
    ADD CONSTRAINT detalle_documento_cobranza_pkey PRIMARY KEY (det_doc_co_id_int);


--
-- Name: detalle_documento detalle_documento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_documento
    ADD CONSTRAINT detalle_documento_pkey PRIMARY KEY (dtdoc_id_int);


--
-- Name: detalle_liquidacion detalle_liquidacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_liquidacion
    ADD CONSTRAINT detalle_liquidacion_pkey PRIMARY KEY (dtliq_id_int);


--
-- Name: detalle_recibo detalle_recibo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_recibo
    ADD CONSTRAINT detalle_recibo_pkey PRIMARY KEY (det_recibo_id_int);


--
-- Name: documento_cobranza documento_cobranza_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT documento_cobranza_pkey PRIMARY KEY (doc_co_id_int);


--
-- Name: documentos documentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_pkey PRIMARY KEY (doc_id_int);


--
-- Name: estados_cotizacion estados_cotizacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_cotizacion
    ADD CONSTRAINT estados_cotizacion_pkey PRIMARY KEY (est_cot_id_int);


--
-- Name: forma_pago forma_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forma_pago
    ADD CONSTRAINT forma_pago_pkey PRIMARY KEY (form_id_int);


--
-- Name: historial_cotizaciones historial_cotizaciones_hist_cot_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_cotizaciones
    ADD CONSTRAINT historial_cotizaciones_hist_cot_uuid_key UNIQUE (hist_cot_uuid);


--
-- Name: historial_cotizaciones historial_cotizaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_cotizaciones
    ADD CONSTRAINT historial_cotizaciones_pkey PRIMARY KEY (hist_cot_id_int);


--
-- Name: liquidacion liquidacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacion
    ADD CONSTRAINT liquidacion_pkey PRIMARY KEY (liq_id_int);


--
-- Name: natural_juridico natural_juridico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.natural_juridico
    ADD CONSTRAINT natural_juridico_pkey PRIMARY KEY (nat_jur_id_int);


--
-- Name: observacion_liquidacion observacion_liquidacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observacion_liquidacion
    ADD CONSTRAINT observacion_liquidacion_pkey PRIMARY KEY (obliq_id_int);


--
-- Name: operador operador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operador
    ADD CONSTRAINT operador_pkey PRIMARY KEY (opr_id_int);


--
-- Name: pago_pax pago_pax_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_pax
    ADD CONSTRAINT pago_pax_pkey PRIMARY KEY (pax_id_int);


--
-- Name: persona_juridica persona_juridica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_juridica
    ADD CONSTRAINT persona_juridica_pkey PRIMARY KEY (per_jurd_id_int);


--
-- Name: persona_natural persona_natural_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_natural
    ADD CONSTRAINT persona_natural_pkey PRIMARY KEY (per_nat_id_int);


--
-- Name: personas_cotizaciones personas_cotizaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_cotizaciones
    ADD CONSTRAINT personas_cotizaciones_pkey PRIMARY KEY (cot_id_int, per_id_int);


--
-- Name: personas personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas
    ADD CONSTRAINT personas_pkey PRIMARY KEY (per_id_int);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (prod_id_int);


--
-- Name: proveedor_colaborador proveedor_colaborador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor_colaborador
    ADD CONSTRAINT proveedor_colaborador_pkey PRIMARY KEY (prov_col_id_int);


--
-- Name: proveedor_contacto proveedor_contacto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor_contacto
    ADD CONSTRAINT proveedor_contacto_pkey PRIMARY KEY (prov_cont_id_int);


--
-- Name: proveedor_grupo_contacto proveedor_grupo_contacto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor_grupo_contacto
    ADD CONSTRAINT proveedor_grupo_contacto_pkey PRIMARY KEY (prov_grup_id_int);


--
-- Name: proveedor proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT proveedor_pkey PRIMARY KEY (prov_id_int);


--
-- Name: recibo recibo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT recibo_pkey PRIMARY KEY (recibo_id_int);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (rol_id);


--
-- Name: sucursal sucursal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sucursal
    ADD CONSTRAINT sucursal_pkey PRIMARY KEY (suc_id_int);


--
-- Name: telefonos_personas telefonos_personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telefonos_personas
    ADD CONSTRAINT telefonos_personas_pkey PRIMARY KEY (tel_id_int);


--
-- Name: persona_natural uker65wrb2uydwecgm16jcxhdit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_natural
    ADD CONSTRAINT uker65wrb2uydwecgm16jcxhdit UNIQUE (per_id_int);


--
-- Name: recibo ukjuhiyw7xh1cei81bneiegshmo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT ukjuhiyw7xh1cei81bneiegshmo UNIQUE (cot_id_int);


--
-- Name: documentos ukm0ihowqs11vxdax5u5klhjf34; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT ukm0ihowqs11vxdax5u5klhjf34 UNIQUE (doc_tipo_vac);


--
-- Name: documento_cobranza ukpw02lab8t4gmcvxbd7daumjxc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT ukpw02lab8t4gmcvxbd7daumjxc UNIQUE (cot_id_int);


--
-- Name: liquidacion ukq50tl0c0tclsb71e15ymwxfdb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacion
    ADD CONSTRAINT ukq50tl0c0tclsb71e15ymwxfdb UNIQUE (cot_id_int);


--
-- Name: persona_natural ukrhp51a0xrmty08rhwgk0h1f7k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_natural
    ADD CONSTRAINT ukrhp51a0xrmty08rhwgk0h1f7k UNIQUE (via_id_int);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (usr_id_int);


--
-- Name: viajeros_frecuente viajeros_frecuente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.viajeros_frecuente
    ADD CONSTRAINT viajeros_frecuente_pkey PRIMARY KEY (via_frec_id_int);


--
-- Name: viajeros viajeros_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.viajeros
    ADD CONSTRAINT viajeros_pkey PRIMARY KEY (via_id_int);


--
-- Name: detalle_documento fk21lbxfoqa1sarsuiq4u2xgokx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_documento
    ADD CONSTRAINT fk21lbxfoqa1sarsuiq4u2xgokx FOREIGN KEY (per_nat_id_int) REFERENCES public.persona_natural(per_nat_id_int);


--
-- Name: recibo fk2khhpo0m0tt934s0crv656hm1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fk2khhpo0m0tt934s0crv656hm1 FOREIGN KEY (per_jur_id_int) REFERENCES public.persona_juridica(per_jurd_id_int);


--
-- Name: proveedor_colaborador fk2lsfq8etps3gpghpcmrqv5dbd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor_colaborador
    ADD CONSTRAINT fk2lsfq8etps3gpghpcmrqv5dbd FOREIGN KEY (prov_id_int) REFERENCES public.proveedor(prov_id_int);


--
-- Name: observacion_liquidacion fk3tue9wdns3umqj2ni4qtcsrma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observacion_liquidacion
    ADD CONSTRAINT fk3tue9wdns3umqj2ni4qtcsrma FOREIGN KEY (liq_id_int) REFERENCES public.liquidacion(liq_id_int);


--
-- Name: detalle_cotizacion fk3urijhlyjagmffs1dht0a2gau; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_cotizacion
    ADD CONSTRAINT fk3urijhlyjagmffs1dht0a2gau FOREIGN KEY (cat_id_int) REFERENCES public.categorias(cat_id_int);


--
-- Name: recibo fk40hys94mcdkuorsno5mslulto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fk40hys94mcdkuorsno5mslulto FOREIGN KEY (form_id_int) REFERENCES public.forma_pago(form_id_int);


--
-- Name: persona_natural fk4bq4yl3v370am1arm1x2hbnkj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_natural
    ADD CONSTRAINT fk4bq4yl3v370am1arm1x2hbnkj FOREIGN KEY (via_id_int) REFERENCES public.viajeros(via_id_int);


--
-- Name: usuarios fk4gi7p5vodrpw4gr72cuvtcasp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk4gi7p5vodrpw4gr72cuvtcasp FOREIGN KEY (rol_id) REFERENCES public.role(rol_id);


--
-- Name: cotizaciones fk4xaltx5ag2m9beoqwc7dapd89; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT fk4xaltx5ag2m9beoqwc7dapd89 FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: recibo fk5f7krdvg087nhl8pksy62plhb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fk5f7krdvg087nhl8pksy62plhb FOREIGN KEY (cot_id_int) REFERENCES public.cotizaciones(cot_id_int);


--
-- Name: viajeros_frecuente fk6qji2vwulhb796dk4y4ds8bv3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.viajeros_frecuente
    ADD CONSTRAINT fk6qji2vwulhb796dk4y4ds8bv3 FOREIGN KEY (via_id_int) REFERENCES public.viajeros(via_id_int);


--
-- Name: personas_cotizaciones fk6rd1hqiwvagc5op0885madr1q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_cotizaciones
    ADD CONSTRAINT fk6rd1hqiwvagc5op0885madr1q FOREIGN KEY (cot_id_int) REFERENCES public.cotizaciones(cot_id_int);


--
-- Name: detalle_documento fk6y790irfd2lu6ys0uc884pgm3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_documento
    ADD CONSTRAINT fk6y790irfd2lu6ys0uc884pgm3 FOREIGN KEY (doc_id_int) REFERENCES public.documentos(doc_id_int);


--
-- Name: historial_cotizaciones fk700l3r1vp4x08an04ch1wsko4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_cotizaciones
    ADD CONSTRAINT fk700l3r1vp4x08an04ch1wsko4 FOREIGN KEY (cot_id_int) REFERENCES public.cotizaciones(cot_id_int);


--
-- Name: proveedor_contacto fk7c9jjxkqijrnkjas78a1eji5n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor_contacto
    ADD CONSTRAINT fk7c9jjxkqijrnkjas78a1eji5n FOREIGN KEY (prov_id_int) REFERENCES public.proveedor(prov_id_int);


--
-- Name: persona_juridica fk871g9vlcfedj69901awu3g03m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_juridica
    ADD CONSTRAINT fk871g9vlcfedj69901awu3g03m FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: cotizaciones fk8fgq4ue35s2aq1qpa0k93auff; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT fk8fgq4ue35s2aq1qpa0k93auff FOREIGN KEY (cou_id_int) REFERENCES public.counter(cou_id_int);


--
-- Name: detalle_recibo fk8mne1yg347k3m9ku50e8eh05x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_recibo
    ADD CONSTRAINT fk8mne1yg347k3m9ku50e8eh05x FOREIGN KEY (prod_id_int) REFERENCES public.productos(prod_id_int);


--
-- Name: detalle_liquidacion fk8qw2u8fmeqac450comcg929gk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_liquidacion
    ADD CONSTRAINT fk8qw2u8fmeqac450comcg929gk FOREIGN KEY (opr_id_int) REFERENCES public.operador(opr_id_int);


--
-- Name: cotizaciones fk95oae06nycdbrmssmhrw50ruq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT fk95oae06nycdbrmssmhrw50ruq FOREIGN KEY (carp_id_padr_int) REFERENCES public.carpetas(carp_id_int);


--
-- Name: cotizaciones fk9d5ar7hurrv0re3611ewtbcqj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT fk9d5ar7hurrv0re3611ewtbcqj FOREIGN KEY (est_cot_id_int) REFERENCES public.estados_cotizacion(est_cot_id_int);


--
-- Name: liquidacion fk9onrq7uvtubi5h9sydrpamco5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacion
    ADD CONSTRAINT fk9onrq7uvtubi5h9sydrpamco5 FOREIGN KEY (form_id_int) REFERENCES public.forma_pago(form_id_int);


--
-- Name: detalle_liquidacion fk9sj0umbmt831jabmp9i7dcroa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_liquidacion
    ADD CONSTRAINT fk9sj0umbmt831jabmp9i7dcroa FOREIGN KEY (liq_id_int) REFERENCES public.liquidacion(liq_id_int);


--
-- Name: detalle_liquidacion fka5a2t6xwr9lx9nrv7fpwgl2px; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_liquidacion
    ADD CONSTRAINT fka5a2t6xwr9lx9nrv7fpwgl2px FOREIGN KEY (prod_id_int) REFERENCES public.productos(prod_id_int);


--
-- Name: persona_natural fkaf60qdqegdjou91985s0j4s4k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_natural
    ADD CONSTRAINT fkaf60qdqegdjou91985s0j4s4k FOREIGN KEY (cat_per_id_int) REFERENCES public.categorias_personas(cat_per_id_int);


--
-- Name: cotizaciones fkb9lwciyhu77g8oq3avm4lr2d9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT fkb9lwciyhu77g8oq3avm4lr2d9 FOREIGN KEY (form_id_int) REFERENCES public.forma_pago(form_id_int);


--
-- Name: detalle_cotizacion fkbso2dvxhkgchowpi2l6rp8rmb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_cotizacion
    ADD CONSTRAINT fkbso2dvxhkgchowpi2l6rp8rmb FOREIGN KEY (prod_id_int) REFERENCES public.productos(prod_id_int);


--
-- Name: documento_cobranza fkc2qh5fe98k21y78nkf1r3o4tc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkc2qh5fe98k21y78nkf1r3o4tc FOREIGN KEY (per_jur_id_int) REFERENCES public.persona_juridica(per_jurd_id_int);


--
-- Name: detalle_documento_cobranza fkc7pxn55liuhww8ovm1wq95ytl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_documento_cobranza
    ADD CONSTRAINT fkc7pxn55liuhww8ovm1wq95ytl FOREIGN KEY (prod_id_int) REFERENCES public.productos(prod_id_int);


--
-- Name: detalle_documento_cobranza fkd2mx308o5118sod6aneteapcw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_documento_cobranza
    ADD CONSTRAINT fkd2mx308o5118sod6aneteapcw FOREIGN KEY (doc_co_id_int) REFERENCES public.documento_cobranza(doc_co_id_int);


--
-- Name: detalle_cotizacion fkfm45fy05sid2e9hqd4uy0pqcm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_cotizacion
    ADD CONSTRAINT fkfm45fy05sid2e9hqd4uy0pqcm FOREIGN KEY (opr_id_int) REFERENCES public.operador(opr_id_int);


--
-- Name: telefonos_personas fkfys38sakbwsloonnlwktrlmmy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telefonos_personas
    ADD CONSTRAINT fkfys38sakbwsloonnlwktrlmmy FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: historial_cotizaciones fkg077wfdn396sqafwwphht9rnx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_cotizaciones
    ADD CONSTRAINT fkg077wfdn396sqafwwphht9rnx FOREIGN KEY (usr_id_int) REFERENCES public.usuarios(usr_id_int);


--
-- Name: proveedor_contacto fkg9dysn263rp64efo8kudueu1y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedor_contacto
    ADD CONSTRAINT fkg9dysn263rp64efo8kudueu1y FOREIGN KEY (prov_grup_id_int) REFERENCES public.proveedor_grupo_contacto(prov_grup_id_int);


--
-- Name: documento_cobranza fkgp667an3jlj8m5nijtddmj8cm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkgp667an3jlj8m5nijtddmj8cm FOREIGN KEY (suc_id_int) REFERENCES public.sucursal(suc_id_int);


--
-- Name: detalle_cotizacion fkgwbc4b7c116bwxfpk8t8p9sqj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_cotizacion
    ADD CONSTRAINT fkgwbc4b7c116bwxfpk8t8p9sqj FOREIGN KEY (prov_id_int) REFERENCES public.proveedor(prov_id_int);


--
-- Name: correos_personas fkh4ffx1vrjc4dyykkai4xh1rxt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.correos_personas
    ADD CONSTRAINT fkh4ffx1vrjc4dyykkai4xh1rxt FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: pago_pax fkid6c2c0wdc1t01f7utlb6pku3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_pax
    ADD CONSTRAINT fkid6c2c0wdc1t01f7utlb6pku3 FOREIGN KEY (liq_id_int) REFERENCES public.liquidacion(liq_id_int);


--
-- Name: liquidacion fkil152bs9g99sej7aficmg7hdq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacion
    ADD CONSTRAINT fkil152bs9g99sej7aficmg7hdq FOREIGN KEY (carp_id_padr_int) REFERENCES public.carpetas(carp_id_int);


--
-- Name: recibo fkjyhbsx1oysl5snexkht2n4gpt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fkjyhbsx1oysl5snexkht2n4gpt FOREIGN KEY (usr_id_int) REFERENCES public.usuarios(usr_id_int);


--
-- Name: recibo fkk07g7fotnp9xc15v95ycbjkly; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fkk07g7fotnp9xc15v95ycbjkly FOREIGN KEY (suc_id_int) REFERENCES public.sucursal(suc_id_int);


--
-- Name: documento_cobranza fkkg3rsgmw0t8by4g9btv2kgsmc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkkg3rsgmw0t8by4g9btv2kgsmc FOREIGN KEY (dtdoc_id_int) REFERENCES public.detalle_documento(dtdoc_id_int);


--
-- Name: detalle_liquidacion fkm8gtn3cll8r57hdlhqi3oc8bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_liquidacion
    ADD CONSTRAINT fkm8gtn3cll8r57hdlhqi3oc8bh FOREIGN KEY (prov_id_int) REFERENCES public.proveedor(prov_id_int);


--
-- Name: documento_cobranza fkmpeir66u0oproe9j7pwhxc04k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkmpeir66u0oproe9j7pwhxc04k FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: recibo fkmrvi193ejb483k4y3odpilg12; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fkmrvi193ejb483k4y3odpilg12 FOREIGN KEY (dtdoc_id_int) REFERENCES public.detalle_documento(dtdoc_id_int);


--
-- Name: cotizaciones fkn0k3fj6xindpnt6l8758xl3dv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotizaciones
    ADD CONSTRAINT fkn0k3fj6xindpnt6l8758xl3dv FOREIGN KEY (suc_id_int) REFERENCES public.sucursal(suc_id_int);


--
-- Name: usuarios fkneveeyegcyu4l85m2pi1gt7ul; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fkneveeyegcyu4l85m2pi1gt7ul FOREIGN KEY (suc_id_int) REFERENCES public.sucursal(suc_id_int);


--
-- Name: detalle_recibo fko8l1v7tra8j72p99fithipsub; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_recibo
    ADD CONSTRAINT fko8l1v7tra8j72p99fithipsub FOREIGN KEY (recibo_id_int) REFERENCES public.recibo(recibo_id_int);


--
-- Name: documento_cobranza fkoaqnx6tmru6lf3t1deyjuogdd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkoaqnx6tmru6lf3t1deyjuogdd FOREIGN KEY (cot_id_int) REFERENCES public.cotizaciones(cot_id_int);


--
-- Name: liquidacion fkof35q0gg35qrhl8htfwngp534; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacion
    ADD CONSTRAINT fkof35q0gg35qrhl8htfwngp534 FOREIGN KEY (prod_id_int) REFERENCES public.productos(prod_id_int);


--
-- Name: detalle_cotizacion fkov47avvta6mg6iwvgfpy16xqu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_cotizacion
    ADD CONSTRAINT fkov47avvta6mg6iwvgfpy16xqu FOREIGN KEY (cot_id_int) REFERENCES public.cotizaciones(cot_id_int);


--
-- Name: liquidacion fkpc6g66kqyt1r9q8royyn4qjo6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidacion
    ADD CONSTRAINT fkpc6g66kqyt1r9q8royyn4qjo6 FOREIGN KEY (cot_id_int) REFERENCES public.cotizaciones(cot_id_int);


--
-- Name: recibo fkpxdixaynfaajdjqs3jn8t8a61; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fkpxdixaynfaajdjqs3jn8t8a61 FOREIGN KEY (carp_id_int) REFERENCES public.carpetas(carp_id_int);


--
-- Name: natural_juridico fkq1bt1q2n6ia7ud57c9a1x9ir2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.natural_juridico
    ADD CONSTRAINT fkq1bt1q2n6ia7ud57c9a1x9ir2 FOREIGN KEY (per_jur_id_int) REFERENCES public.persona_juridica(per_jurd_id_int);


--
-- Name: documento_cobranza fkq3nftxvqb03xwtc95fae4q2dw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkq3nftxvqb03xwtc95fae4q2dw FOREIGN KEY (usr_id_int) REFERENCES public.usuarios(usr_id_int);


--
-- Name: historial_cotizaciones fkr4xfp14bygr7am2iaa7vw1yp6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_cotizaciones
    ADD CONSTRAINT fkr4xfp14bygr7am2iaa7vw1yp6 FOREIGN KEY (est_cot_id_int) REFERENCES public.estados_cotizacion(est_cot_id_int);


--
-- Name: detalle_liquidacion fkrdewvk8101h9ouopb51yd8xr3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_liquidacion
    ADD CONSTRAINT fkrdewvk8101h9ouopb51yd8xr3 FOREIGN KEY (via_id_int) REFERENCES public.viajeros(via_id_int);


--
-- Name: recibo fkri8heeca2l5ma4yyujo57i0ll; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recibo
    ADD CONSTRAINT fkri8heeca2l5ma4yyujo57i0ll FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: documento_cobranza fkrkqpgmhwtva9j308pp8ubpehe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fkrkqpgmhwtva9j308pp8ubpehe FOREIGN KEY (form_id_int) REFERENCES public.forma_pago(form_id_int);


--
-- Name: persona_natural fkrmqjaa7n0pnrcbpexgndn4c7t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_natural
    ADD CONSTRAINT fkrmqjaa7n0pnrcbpexgndn4c7t FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: pago_pax fksmblu7ggd79b79llths30kudu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_pax
    ADD CONSTRAINT fksmblu7ggd79b79llths30kudu FOREIGN KEY (form_id_int) REFERENCES public.forma_pago(form_id_int);


--
-- Name: personas_cotizaciones fksxmkp9m4ky7w68vlr3lsuds92; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_cotizaciones
    ADD CONSTRAINT fksxmkp9m4ky7w68vlr3lsuds92 FOREIGN KEY (per_id_int) REFERENCES public.personas(per_id_int);


--
-- Name: natural_juridico fkt5o11if0hclyesou67gea3gn7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.natural_juridico
    ADD CONSTRAINT fkt5o11if0hclyesou67gea3gn7 FOREIGN KEY (per_nat_id_int) REFERENCES public.persona_natural(per_nat_id_int);


--
-- Name: carpetas fkt8g1cp5sjtubc3bk6yflopauy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carpetas
    ADD CONSTRAINT fkt8g1cp5sjtubc3bk6yflopauy FOREIGN KEY (car_id_padr_int) REFERENCES public.carpetas(carp_id_int);


--
-- Name: documento_cobranza fktikp5dlsdssyitonnh51i7qjs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_cobranza
    ADD CONSTRAINT fktikp5dlsdssyitonnh51i7qjs FOREIGN KEY (carp_id_int) REFERENCES public.carpetas(carp_id_int);


--
-- PostgreSQL database dump complete
--

