# Identificador del proyecto (debe coincidir con el Project key)
sonar.projectKey=INFRA-UPAO_everywheretravel
sonar.projectName=everywheretravel
sonar.projectVersion=1.1
sonar.sources=.
sonar.sourceEncoding=UTF-8