name: Deploy prod

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy a prod
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit
