name: Deploy dev

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy a dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit
