name: Terraform Plan (PR)

on:
  pull_request:
    paths:
      - "iac/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: terraform plan (workspace dev)
    runs-on: ubuntu-latest